### ISSUE TITLE
Collection Configuration DisableCreate() removes ability to update.

### ISSUE THREAD

**Issue by jho-md** [umbraco/Umbraco.UIBuilder.Issues#151]
**Describe the bug**
When configuring a collection with `collectionConfig.DisableCreate()`, it takes away the save button even when updating a collection.

**Steps To Reproduce**
1. Configure a collection.
2. Create an entity in this collection.
3. Configure the collection with DisableCreate()
4. Navigate to your created entity.
5. Attempt to update the entity.
6. See that the save button disappears and users are unable to update an existing entity.

**Expected behavior**
DisableCreate() should only disable creation not updates. The save button should still be there for updating existing entities.

**Environment (please complete the following information):**
 - Server OS: Windows
 - Browser: Chrome
 - Umbraco Version: 15.3.0
 - Product Version: 15.1.2

---
_This item has been added to our backlog AB#51835_

**Comment by andrejd22** [comment]
@acoumb Any updates on this issue?

**Comment by acoumb** [comment]
@andrejd22 it is in progress, I expect it to go out with the next patch release at the start of next week.

**Comment by acoumb** [comment]
Hi @jho-md , @andrejd22 ,

This is now fixed in version [`15.1.4`](https://www.nuget.org/packages/Umbraco.UIBuilder/15.1.4).

Thanks,
Adrian

**Comment by krebil** [comment]
@acoumb This seems to still be an issue in 15.1.5 

I have a config that looks like this 

<img width="771" alt="Image" src="https://github.com/user-attachments/assets/9bdbd441-1956-4f73-a198-26745b1eb22c" />

And I still don't have a save button

![Image](https://github.com/user-attachments/assets/13820b95-8fe2-40ac-8286-536ef4977798)
